### ISSUE TITLE
jsonpath get keys not compatible

### ISSUE THREAD

**Issue by liuweidong88** [jg-rp/python-jsonpath#38]
I have a json like this
```json
{
    "task_tag": "blade_appearance_detect",
    "image_type": "base64",
    "extra_args": [
        {
            "model": "crack",
            "param": {
                "conf": 0.66,
                "iou": 0.25
            }
        },
        {
            "model": "damaged",
            "param": {
                "conf": 0.3,
                "iou": 0.25
            }
        }
    ]
}
```
I want param's all keys, expect ['conf', 'iou', 'conf', 'iou'],
I use `jsonpath.findall('$..param~', ret)`  to get right result, but other syntax is "$..param.*~", not compatible.

**Comment by jg-rp** [comment]
Hi @liuweidong88,

You can change the default keys selector by subclassing `JSONPathEnvironment` and setting the `keys_selector_token` class attribute. Then use the environment's `findall()` method instead of the package-level `findall()` function.

This requires Python JSONPath **version 0.10.1** (just released). There was a bug preventing `*` from being used as an environment controlled token (see #39).

```python
from jsonpath import JSONPathEnvironment


class MyJSONPathEnvironment(JSONPathEnvironment):
    keys_selector_token = "*~"


data = {
    "task_tag": "blade_appearance_detect",
    "image_type": "base64",
    "extra_args": [
        {"model": "crack", "param": {"conf": 0.66, "iou": 0.25}},
        {"model": "damaged", "param": {"conf": 0.3, "iou": 0.25}},
    ],
}

env = MyJSONPathEnvironment()
print(env.findall("$..param.*~", data))  # ['conf', 'iou', 'conf', 'iou']
```

[Documentation for this](https://jg-rp.github.io/python-jsonpath/advanced/#keys-selector) and other environment customizations is on my to do list.

**Comment by liuweidong88** [comment]
thanks
