### ISSUE TITLE
unexpected token 'and' / 'or' for properties

### ISSUE THREAD

**Issue by torbenw** [jg-rp/python-jsonpath#72]
This works:
`jsonpath.findall('$.orders', json_object)`
`jsonpath.findall('$.test', json_object)`
`jsonpath.findall('test', json_object)`

This does not work: 
`jsonpath.findall('orders', json_object)` -> `JSONPathSyntaxError: unexpected token 'or', line 1, column 0`
`jsonpath.findall('andy', json_object)` -> `JSONPathSyntaxError: unexpected token 'and', line 1, column 0`

According to the documentation the '$.' part is optional.

**Comment by jg-rp** [comment]
Thank you, @torbenw. Should be fixed in version 1.2.2, now released.

Names/property selectors that match a reserved word exactly, and where we can't tell the difference using a preceding `.`, will still need to use quoted syntax, like `["and"]`. I've added a list of the default reserved words to the docs [here](https://jg-rp.github.io/python-jsonpath/syntax/#properties-thing-thing-or-thing).
